#!/usr/bin/env python3

import argparse
import json
import subprocess
import time
from pathlib import Path


SCHEME_PATH = Path.home() / ".local/state/caelestia/scheme.json"
OUTPUT_PATH = Path.home() / ".config/hypr/dynamic-border.conf"


def normalize_rgba(value: str, alpha: str = "ff") -> str:
    value = (value or "").strip().lower().lstrip("#")

    if len(value) == 8:
        return value

    if len(value) == 6:
        return f"{value}{alpha}"

    return f"ffffffff" if alpha == "ff" else f"595959{alpha}"


def build_border_values(colours: dict[str, str]) -> tuple[str, str]:
    active_primary = normalize_rgba(
        colours.get("primary") or colours.get("surfaceTint") or colours.get("primaryFixed")
    )
    active_secondary = normalize_rgba(
        colours.get("secondary") or colours.get("secondaryFixedDim") or colours.get("tertiary")
    )
    active_tertiary = normalize_rgba(
        colours.get("tertiary") or colours.get("primaryFixedDim") or colours.get("secondary")
    )
    inactive = normalize_rgba(
        colours.get("outlineVariant") or colours.get("surfaceVariant") or colours.get("outline"),
        alpha="aa",
    )

    active_value = (
        f"rgba({active_primary}) rgba({active_secondary}) rgba({active_tertiary}) 45deg"
    )
    inactive_value = f"rgba({inactive})"
    return active_value, inactive_value


def write_config(active_value: str, inactive_value: str) -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(
        (
            "# Generated by ~/scripts/hypr-border-sync.py\n"
            "general {\n"
            f"    col.active_border = {active_value}\n"
            f"    col.inactive_border = {inactive_value}\n"
            "}\n"
        ),
        encoding="utf-8",
    )


def apply_live(active_value: str, inactive_value: str) -> None:
    subprocess.run(
        ["hyprctl", "keyword", "general:col.active_border", active_value],
        check=False,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    subprocess.run(
        ["hyprctl", "keyword", "general:col.inactive_border", inactive_value],
        check=False,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def load_scheme_values() -> tuple[str, str] | None:
    try:
        data = json.loads(SCHEME_PATH.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return None

    colours = data.get("colours")
    if not isinstance(colours, dict):
        return None

    return build_border_values(colours)


def sync_once() -> tuple[str, str] | None:
    values = load_scheme_values()
    if values is None:
        return None

    active_value, inactive_value = values
    write_config(active_value, inactive_value)
    apply_live(active_value, inactive_value)
    return values


def watch(interval: float) -> int:
    last_mtime_ns = None
    last_values = None

    while True:
        try:
            stat = SCHEME_PATH.stat()
            mtime_ns = stat.st_mtime_ns
        except FileNotFoundError:
            mtime_ns = None

        if mtime_ns != last_mtime_ns:
            values = sync_once()
            if values is not None:
                last_values = values
            last_mtime_ns = mtime_ns
        elif last_values is None:
            last_values = sync_once()

        time.sleep(interval)


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync Hyprland border colors to the current wallpaper scheme.")
    parser.add_argument("--watch", action="store_true", help="keep watching the Caelestia scheme file for updates")
    parser.add_argument("--interval", type=float, default=1.0, help="watch polling interval in seconds")
    args = parser.parse_args()

    sync_once()

    if args.watch:
        return watch(max(args.interval, 0.2))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
